NumberChecker first commit
Johanna1988/JavaCourseNew pull request #5
Opened 2022-05-28 18:38 UTC by Johanna1988

2022-05-28 18:44 UTC, Maks-Chornyi commented
First thing: Always use curly brackets when you use `if` `for` statements. 

So bad practice: 
```
if (a > b) 
   System.out.println("Some text");
```

Good practice: 
```
if (a > b {
   System.out.println("Good practice");
}
```

2022-05-28 19:03 UTC, Maks-Chornyi requested changes
Good, it works. Check my comments :)

2022-05-28 19:03 UTC, Maks-Chornyi commented on src/main/java/checkers/NumberChecker.java
> +            System.out.println("Your number is positive");
what if user put `0`? If statement (11-14 lines) will be skipped. So when you use
```
 if (condition) {
    //some code
 } else if (some condition) {
   //some code 
 }
 ```
 put also `else` case. 
 
```
 if (condition) {
    //some code
 } else if (some condition) {
   //some code 
 } else {
   //some code in case conditions above were skipped
   }
```

2022-05-28 19:03 UTC, Maks-Chornyi commented on src/main/java/checkers/NumberChecker.java
> +        }
Look at your 19-23 lines. 
It's not logically use `else if` statement in this case. Let's think. If condition in line 19 is `false`, it means that number is odd. In all cases. So instead of using `if (condition) { } else if (condition) { }` statement. just use `if (condition) {} else {}` statement.

2022-05-28 19:03 UTC, Maks-Chornyi commented on src/main/java/checkers/NumberChecker.java
> +        int number2 = scan2.nextInt();
Look at line 17. You create new object of type `Scanner` and give the name `scan2`. But it's not necessary.
you can avoid creating this object. Just in line 18 instead of calling method in `scan2` object, just call method on `scan` object which you created in line 9

2022-05-28 21:08 UTC, Johanna1988 commented on src/main/java/checkers/NumberChecker.java
> +            System.out.println("Your number is positive");
I have added else case, thanks for your comments

2022-05-28 21:08 UTC, Johanna1988 commented on src/main/java/checkers/NumberChecker.java
> +        }
Fixed, thanks

2022-05-28 21:08 UTC, Johanna1988 commented on src/main/java/checkers/NumberChecker.java
> +        int number2 = scan2.nextInt();
Fixed, thanks

2022-05-30 07:52 UTC, Maks-Chornyi approved these changes
LGTM

2022-05-30 19:39 UTC, merged